### ISSUE TITLE
1.20.1 Fabric Crash

### ISSUE THREAD

**Issue by 533kr** [umjammer/jlayer#7]
It may be interacting oddly with another one of my (many, many) mods, but the crash log does name Tense Ambience specifically, so I've had to remove it, as it's happened twice so far while caving.

```
Description: Unexpected error

java.lang.IllegalArgumentException: Requested value 6.05029 exceeds allowable maximum value 6.0206.
	at java.desktop/javax.sound.sampled.FloatControl.setValue(FloatControl.java:199)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectDL$Gain.setValue(DirectAudioDevice.java:815)
	at net.cyberking42.tenseambience.SoundClip.setVolume(SoundClip.java:95)
	at net.cyberking42.tenseambience.SoundManager.onClientTick(SoundManager.java:70)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$dgn000$fabric-lifecycle-events-v1$onEndTick(class_310.java:19043)
	at net.minecraft.class_310.method_1574(class_310.java:1957)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

The full crashlog: 
[crash-2024-08-15_03.06.54-client.txt](https://github.com/user-attachments/files/16622355/crash-2024-08-15_03.06.54-client.txt)

**Comment by umjammer** [comment]
why do u ask me?
it seems that **Tense Ambience** sets invalid volume value.
